id: AA1A6AC7C
title: Short Tsok Offering to the Powerful Lady Kurukullā
type: translation
pechas:
- I162BA66C
- I2FD93343
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:38:09.484399
  last_modified_at: 2023-01-04 12:38:09.484408
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I162BA66C/9685: 88E2
  I2FD93343/2A18: 88E2
